# Module: docker
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.6/metricbeat-module-docker.html

- module: docker
  metricsets:
   - container
   - cpu
   - diskio
   - healthcheck
   - info
   - memory
   - network
  period: 10s
  hosts: ["unix:///var/run/docker.sock"]
